name: "Setup MinIO client"
description: "Sets up MinIO client (And it caches it, too!)"
author: Vladimir Levin
branding:
  icon: code
  color: purple
inputs:
  mc_url:
    description: URL to obtain `mc` from
    required: false
    default: "https://dl.min.io/client/mc/release/{platform}-{arch}/mc"
  use_cache:
    description: MC doesn't have `real` versions, you can pass `use_cache=false` to fetch latest version every time
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'action/index.js'
